name: CustomRewards
version: '${project.version}'
main: skippyall.custom_rewards.CustomRewards
api-version: 1.19
commands:
  reward:
    description: Gets your daily reward.
    usage: /reward
    permission: custom_rewards.command
