name: CustomRewards
version: '${project.version}'
main: skippyall.custom_rewards.CustomRewards
api-version: 1.19
depend: [CommandAPI]
permissions:
  custom_rewards.give:
    default: op
    description: Enables /reward give
  custom_rewards.claim:
    description: Enables /reward claim and /reward
    default: true